-- Agent-written dossier narratives — one cached row per technology per day.
-- Generated by the Dossier Analyst agent (Agents_prompt/Dossier_Analyst_Agent.md,
-- TOQAN_DOSSIER) during Refresh all / the scheduled pipeline, NEVER on page
-- load. The dossier page shows the narrative when one exists for the current
-- assembly; the deterministic composed read remains the always-available
-- fallback, so a missing key or a bad agent day degrades gracefully.
CREATE TABLE IF NOT EXISTS tech_narratives (
    tech_key       TEXT NOT NULL,               -- technologies.py registry key
    as_of          DATE NOT NULL,               -- the day the inputs were assembled
    narrative      TEXT NOT NULL,               -- markdown prose (validated: no phantom [S#])
    prompt_version TEXT NOT NULL,               -- e.g. 'dossier-v1'
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tech_key, as_of)               -- idempotent re-runs upsert, never duplicate
);

CREATE INDEX IF NOT EXISTS idx_tech_narratives_latest
    ON tech_narratives (tech_key, as_of DESC);
